spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      environment: local
      partitions: 6
      replicas: 1

server:
  port: 8081

service:
  wallet:
    url: ${WALLET_SERVICE_URL:http://localhost:8082}
  member:
    url: ${MEMBER_SERVICE_URL:http://localhost:8083}
  merchant:
    domain: ${MERCHANT_SERVICE_URL:http://localhost:8084}

---

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false