spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payflow_payment
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: localhost
      port: 6379
